###_______________CLIENT_______________

### API GET 
GET http://localhost:8080/api/v1/client

### API INSERT 
POST http://localhost:8080/api/v1/client
Content-Type: application/json

{
    "id": 0,
    "name": "Via Roma"
}
### API UPDATE 
PUT http://localhost:8080/api/v1/client/1
Content-Type: application/json

{
    "name": "Via Veneza"
}
### API DELETE 
DELETE http://localhost:8080/api/v1/client/1

###_______________EMPLOYEE_______________

### API GET
GET http://localhost:8080/api/v1/employee

### API INSERT - LIDER
POST http://localhost:8080/api/v1/employee
Content-Type: application/json

{
    "id": 0,
    "name": "Carlos Silva",
    "role": "Patrão",
    "leader": null
}

### API INSERT - FUNCIONÁRIO
POST http://localhost:8080/api/v1/employee
Content-Type: application/json

{
    "id": 0,
    "name": "Lorenzo Poncio",
    "role": "Analista I",
    "leader": {
        "id": 1,
        "name": "Carlos Silva",
        "role": "Patrão",
        "leader": null
    }
}
### API UPDATE
PUT http://localhost:8080/api/v1/employee/2
Content-Type: application/json

{
    "name": "Lorenzo Poncio",
    "role": "Analista II",
    "leader": {
        "id": 1,
        "name": "Carlos Silva",
        "role": "Patrão",
        "leader": null
    }
}
### API DELETE
DELETE http://localhost:8080/api/v1/employee/2

###_______________STATUS_______________

### API GET
GET http://localhost:8080/api/v1/status

### API INSERT
POST http://localhost:8080/api/v1/status
Content-Type: application/json

{
    "id": 0,
    "name": "A Iniciar"
}

### API UPDATE
PUT http://localhost:8080/api/v1/status/1
Content-Type: application/json

{
    "name": "Concluído"
}

### API DELETE
DELETE http://localhost:8080/api/v1/deadline-status/1

###_______________DEMAND_______________

### API GET
GET http://localhost:8080/api/v1/demand

### API INSERT
POST http://localhost:8080/api/v1/demand
Content-Type: application/json

{
    "id": 0,
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "A Iniciar"
    },
    "deadline": "2025-05-10"
}

### API UPDATE
PUT http://localhost:8080/api/v1/demand/1
Content-Type: application/json

{
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "Concluído"
    },
    "deadline": "2025-05-10"
}

### API DELETE
DELETE http://localhost:8080/api/v1/demand/1

###_______________PRODUCTION TYPE_______________

### API GET 
GET http://localhost:8080/api/v1/production-type

### API INSERT 
POST http://localhost:8080/api/v1/production-type
Content-Type: application/json

{
    "id": 0,
    "name": "Normal"
}
### API UPDATE 
PUT http://localhost:8080/api/v1/production-type/1
Content-Type: application/json

{
    "name": "Duplo"
}
### API DELETE
DELETE http://localhost:8080/api/v1/production-type/1

###_______________DEADLINE STATUS_______________

### API GET 
GET http://localhost:8080/api/v1/deadline-status

### API INSERT 
POST http://localhost:8080/api/v1/deadline-status
Content-Type: application/json

{
    "id": 0,
    "name": "Em dia"
}
### API UPDATE 
PUT http://localhost:8080/api/v1/deadline-status/1
Content-Type: application/json

{
    "name": "Em atraso"
}
### API DELETE
DELETE http://localhost:8080/api/v1/deadline-status/1

###_______________COLECT_______________

### API GET 
GET http://localhost:8080/api/v1/colect

### API INSERT 
POST http://localhost:8080/api/v1/colect
Content-Type: application/json

{   
    "id": 0,
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "A Iniciar"
    },
    "deadline": "2025-05-10",
    "dataPagamento": "2025-05-05",
    "dataPrimeiroContato": "2025-05-01",
    "dataColetaConcluida": null,
    "tmc": 0
}
### API UPDATE 
PUT http://localhost:8080/api/v1/colect/1
Content-Type: application/json

{
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "A Iniciar"
    },
    "deadline": "2025-05-10",
    "dataPagamento": "2025-05-05",
    "dataPrimeiroContato": "2025-05-01",
    "dataColetaConcluida": "2025-05-08",
    "tmc": 5
}
### API DELETE
DELETE http://localhost:8080/api/v1/colect/1

###_______________PRODUCTION_______________

### API GET 
GET http://localhost:8080/api/v1/production

### API INSERT 
POST http://localhost:8080/api/v1/production
Content-Type: application/json

{   
    "id": 0,
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "A Iniciar"
    },
    "deadline": "2025-05-10",
    "tipo":{
        "id": 1,
        "name": "Normal"
    },
    "dataVencimentoGeral": "2025-05-10",
    "dataVencimentoCriacao": "2025-05-09",
    "prazo":{
        "id": 1,
        "name": "Em dia"
    }
}
### API UPDATE 
PUT http://localhost:8080/api/v1/production/1
Content-Type: application/json

{
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "A Iniciar"
    },
    "deadline": "2025-05-10",
    "tipo":{
        "id": 1,
        "name": "Normal"
    },
    "dataVencimentoGeral": "2025-05-10",
    "dataVencimentoCriacao": "2025-05-01",
    "prazo":{
        "id": 1,
        "name": "Em dia"
    }
}
### API DELETE
DELETE http://localhost:8080/api/v1/production/1

###_______________IMPLEMENTATION_______________

### API GET 
GET http://localhost:8080/api/v1/implementation

### API INSERT 
POST http://localhost:8080/api/v1/implementation
Content-Type: application/json

{   
    "id": 0,
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "A Iniciar"
    },
    "deadline": "2025-05-10",
    "dataVencimento": "2025-05-10",
    "dataInicioImplantacao": "2025-05-10",
    "dataConclusao": null,
    "dataAssinatura": ""
}
### API UPDATE 
PUT http://localhost:8080/api/v1/implementation/1
Content-Type: application/json

{
    "name": "Nova Demanda - Via Roma",
    "responsible": {
        "id": 2,
        "name": "Lorenzo Poncio",
        "role": "Analista I",
        "leader": {
            "id": 1,
            "name": "Carlos Silva",
            "role": "Patrão",
            "leader": null
        }
    },
    "client": {
        "id": 1,
        "name": "Via Roma"
    },
    "status": {
        "id": 1,
        "name": "Concluído"
    },
    "deadline": "2025-05-10",
    "dataVencimento": "2025-05-10",
    "dataInicioImplantacao": "2025-05-10",
    "dataConclusao": "2025-05-10",
    "dataAssinatura": "2025-05-15"
}
### API DELETE
DELETE http://localhost:8080/api/v1/implementation/1