### API GET 
GET http://localhost:8080/api/v1/client

### API INSERT 
POST http://localhost:8080/api/v1/client
Content-Type: application/json

{
    "id": 0,
    "name": "Via Roma"
}
### API UPDATE 
PUT http://localhost:8080/api/v1/client/1
Content-Type: application/json

{
    "name": "Via Veneza"
}
### API DELETE 
DELETE http://localhost:8080/api/v1/client/1

###_______________EMPLOYEE_______________

### API GET
GET http://localhost:8080/api/v1/employee

### API INSERT - LIDER
POST http://localhost:8080/api/v1/employee
Content-Type: application/json

{
    "id": 0,
    "name": "Carlos Silva",
    "role": "Patrão",
    "leader": null
}

### API INSERT - FUNCIONÁRIO
POST http://localhost:8080/api/v1/employee
Content-Type: application/json

{
    "id": 0,
    "name": "Lorenzo Poncio",
    "role": "Analista I",
    "leader": {
        "id": 1,
        "name": "Carlos Silva",
        "role": "Patrão",
        "leader": null
    }
}
### API UPDATE
PUT http://localhost:8080/api/v1/employee/2
Content-Type: application/json

{
    "name": "Lorenzo Poncio",
    "role": "Analista II",
    "leader": {
        "id": 1,
        "name": "Carlos Silva",
        "role": "Patrão",
        "leader": null
    }
}
### API DELETE
DELETE http://localhost:8080/api/v1/employee/2