### API GET 
GET http://localhost:8080/api/v1/client

### API INSERT 
POST http://localhost:8080/api/v1/client
Content-Type: application/json

{
    "id": 0,
    "name": "Via Roma"
}
### API UPDATE 
PUT http://localhost:8080/api/v1/client/1
Content-Type: application/json

{
    "name": "Via Veneza"
}
### API DELETE 
DELETE http://localhost:8080/api/v1/client/1

###----------DEMAND----------

### API GET -----------------------------
GET http://localhost:8080/api/v1/client

### API INSERT -----------------------------
POST http://localhost:8080/api/v1/client
Content-Type: application/json

{
    "id": 0,
    "name": "Via Roma"
}
### API UPDATE -----------------------------
PUT http://localhost:8080/api/v1/client/1
Content-Type: application/json

{
    "name": "Via Veneza"
}
### API DELETE -----------------------------
DELETE http://localhost:8080/api/v1/client/1